version: 2
sources:
  - name: staging
    database: dtc-data-eng-course
    schema: trips_data_all
    tables:
      - name: green_trip_data
      - name: yellow_trip_data
      - name: fhv_trip_data 
